---
# tasks file for Apache
- name: Installe apache
  yum:
   name: httpd
   state: present

- name: disable firewall
  systemd:
   name: firewalld
   state: stopped
   enabled: no

- name: démarre et activate le serveur apache
  systemd:
   name: httpd
   state: started
   enabled: yes
